### ISSUE TITLE
Navbar links broken when in /blog

### ISSUE THREAD

**Issue by adpadillar** [devtimnbr/portfolio#1]
Hey!

I was reading your blogpost (https://timneubauer.dev/blog/copy-code-button-in-astro/) Very helpful btw! But then I navigated to the /blog page and tried using your Navigation bar when on `/blog` to go back to `/#projects` and the link didn't work.

When clicking the `_projects` link from `/blog`, my browser's address bar changes to `https://timneubauer.dev/blog/#projects`, instead of the expected `https://timneubauer.dev/#projects`

I attempted to fork your project to attempt to fix the issue, but it worked fine when on my local server... So I'm submitting an issue just so you're aware of it in case you want to have a look!

> Firefox 113.0.1

**Comment by devtimnbr** [comment]
Hey!

Thank for the comment. Fixed it along with the new astro migration.
